/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Train(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/train_1/train.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        geometry={nodes.carruagem1001.geometry}
        material={nodes.carruagem1001.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.janela.geometry}
        material={nodes.janela.material}
        position={[6.27, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.telhado_cenas.geometry}
        material={nodes.telhado_cenas.material}
        position={[8.86, 1.31, -0.01]}
        scale={[-3.39, 0.12, 0.42]}
      />
      <mesh
        castShadow
        geometry={nodes.telhado_cenas001.geometry}
        material={nodes.telhado_cenas001.material}
        position={[15.44, 1.31, -0.01]}
        scale={[-3.39, 0.12, 0.42]}
      />
      <mesh
        castShadow
        geometry={nodes.antena.geometry}
        material={nodes.antena.material}
        position={[7.88, -0.28, -0.91]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={nodes.acordeao_1.geometry}
        material={nodes.acordeao_1.material}
        position={[12.35, 0.69, 0.05]}
        scale={[0.12, 0.49, 0.45]}
      />
      <mesh
        castShadow
        geometry={nodes.janela006.geometry}
        material={nodes.janela006.material}
        position={[6.27, 0.73, -0.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.34, 0.39, 0.29]}
      />
      <mesh
        castShadow
        geometry={nodes.janela007.geometry}
        material={nodes.janela007.material}
        position={[7.98, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela001.geometry}
        material={nodes.janela001.material}
        position={[8.68, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela002.geometry}
        material={nodes.janela002.material}
        position={[9.4, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela008.geometry}
        material={nodes.janela008.material}
        position={[10.1, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela003.geometry}
        material={nodes.janela003.material}
        position={[11.82, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.Roundcube007.geometry}
        material={nodes.Roundcube007.material}
        position={[4.77, 0.42, -0.4]}
        rotation={[0, 0, -0.19]}
        scale={[0.09, 0.1, 0.08]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1002.geometry}
        material={nodes.carruagem1002.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1003.geometry}
        material={nodes.carruagem1003.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1005.geometry}
        material={nodes.carruagem1005.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1006.geometry}
        material={nodes.carruagem1006.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.janela009.geometry}
        material={nodes.janela009.material}
        position={[6.27, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela010.geometry}
        material={nodes.janela010.material}
        position={[7.98, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela011.geometry}
        material={nodes.janela011.material}
        position={[8.68, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela012.geometry}
        material={nodes.janela012.material}
        position={[9.4, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela013.geometry}
        material={nodes.janela013.material}
        position={[10.1, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela014.geometry}
        material={nodes.janela014.material}
        position={[11.82, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1007.geometry}
        material={nodes.carruagem1007.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1008.geometry}
        material={nodes.carruagem1008.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1009.geometry}
        material={nodes.carruagem1009.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1010.geometry}
        material={nodes.carruagem1010.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1011.geometry}
        material={nodes.carruagem1011.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1.geometry}
        material={nodes.carruagem1.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.parte_debaixo.geometry}
        material={nodes.parte_debaixo.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1013.geometry}
        material={nodes.carruagem1013.material}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.motor_e_rodas_1.geometry}
        material={nodes.motor_e_rodas_1.material}
        position={[7.17, 0.43, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={nodes.motor_e_rodas_2.geometry}
        material={nodes.motor_e_rodas_2.material}
        position={[13.63, 0.43, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={nodes.motor_e_rodas_3.geometry}
        material={nodes.motor_e_rodas_3.material}
        position={[20.22, 0.43, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1014.geometry}
        material={nodes.carruagem1014.material}
        position={[11.4, 0.78, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.Roundcube022.geometry}
        material={nodes.Roundcube022.material}
        position={[4.88, 0.19, 0]}
        scale={[0.18, 0.18, 0.28]}
      />
      <mesh
        castShadow
        geometry={nodes.janela015.geometry}
        material={nodes.janela015.material}
        position={[7.13, 0.73, -0.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.34, 0.39, 0.29]}
      />
      <mesh
        castShadow
        geometry={nodes.janela016.geometry}
        material={nodes.janela016.material}
        position={[7.12, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela017.geometry}
        material={nodes.janela017.material}
        position={[10.95, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela018.geometry}
        material={nodes.janela018.material}
        position={[10.94, 0.73, -0.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.34, 0.39, 0.29]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1012.geometry}
        material={nodes.carruagem1012.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1015.geometry}
        material={nodes.carruagem1015.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1016.geometry}
        material={nodes.carruagem1016.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1017.geometry}
        material={nodes.carruagem1017.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1018.geometry}
        material={nodes.carruagem1018.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1019.geometry}
        material={nodes.carruagem1019.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1020.geometry}
        material={nodes.carruagem1020.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1021.geometry}
        material={nodes.carruagem1021.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1022.geometry}
        material={nodes.carruagem1022.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.acordeao_2.geometry}
        material={nodes.acordeao_2.material}
        position={[18.93, 0.69, 0.05]}
        scale={[0.12, 0.49, 0.45]}
      />
      <mesh
        castShadow
        geometry={nodes.janela004.geometry}
        material={nodes.janela004.material}
        position={[12.88, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1023.geometry}
        material={nodes.carruagem1023.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.janela005.geometry}
        material={nodes.janela005.material}
        position={[13.68, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela019.geometry}
        material={nodes.janela019.material}
        position={[17.56, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela020.geometry}
        material={nodes.janela020.material}
        position={[12.89, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela021.geometry}
        material={nodes.janela021.material}
        position={[17.57, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1024.geometry}
        material={nodes.carruagem1024.material}
        position={[12.55, 0.8, 0]}
        scale={[1.33, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1025.geometry}
        material={nodes.carruagem1025.material}
        position={[19.13, 0.8, 0]}
        scale={[1.33, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.janela022.geometry}
        material={nodes.janela022.material}
        position={[13.7, 0.73, -0.58]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.34, 0.39, 0.29]}
      />
      <mesh
        castShadow
        geometry={nodes.janela023.geometry}
        material={nodes.janela023.material}
        position={[14.58, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela024.geometry}
        material={nodes.janela024.material}
        position={[15.27, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela025.geometry}
        material={nodes.janela025.material}
        position={[15.96, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela026.geometry}
        material={nodes.janela026.material}
        position={[16.67, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela027.geometry}
        material={nodes.janela027.material}
        position={[18.38, 0.73, 0.57]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela028.geometry}
        material={nodes.janela028.material}
        position={[14.51, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela029.geometry}
        material={nodes.janela029.material}
        position={[18.39, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela030.geometry}
        material={nodes.janela030.material}
        position={[16.69, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela031.geometry}
        material={nodes.janela031.material}
        position={[15.95, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.janela032.geometry}
        material={nodes.janela032.material}
        position={[15.23, 0.73, -0.55]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.32, 0.36, 0.27]}
      />
      <mesh
        castShadow
        geometry={nodes.Roundcube037.geometry}
        material={nodes.Roundcube037.material}
        position={[5.41, 0.85, 0.35]}
        scale={0.23}
      />
      <mesh
        castShadow
        geometry={nodes.Plane004.geometry}
        material={materials["Material.010"]}
        position={[4.88, 0.74, 0.03]}
        rotation={[0, 0, -1.88]}
        scale={[-0.07, 1, 0.33]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1001_Roundcube001.geometry}
        material={nodes.carruagem1001_Roundcube001.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela_Plane.geometry}
        material={nodes.janela_Plane.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.telhado_cenas_Roundcube002.geometry}
        material={nodes.telhado_cenas_Roundcube002.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.telhado_cenas001_Roundcube003.geometry}
        material={nodes.telhado_cenas001_Roundcube003.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.acordeao_3.geometry}
        material={nodes.acordeao_3.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela006_Plane008.geometry}
        material={nodes.janela006_Plane008.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela007_Plane011.geometry}
        material={nodes.janela007_Plane011.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela001_Plane012.geometry}
        material={nodes.janela001_Plane012.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela002_Plane013.geometry}
        material={nodes.janela002_Plane013.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela008_Plane014.geometry}
        material={nodes.janela008_Plane014.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela003_Plane015.geometry}
        material={nodes.janela003_Plane015.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.Roundcube044.geometry}
        material={nodes.Roundcube044.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1002_Roundcube008.geometry}
        material={nodes.carruagem1002_Roundcube008.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1003_Roundcube009.geometry}
        material={nodes.carruagem1003_Roundcube009.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1005_Roundcube011.geometry}
        material={nodes.carruagem1005_Roundcube011.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1006_Roundcube012.geometry}
        material={nodes.carruagem1006_Roundcube012.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela009_Plane001.geometry}
        material={nodes.janela009_Plane001.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela010_Plane002.geometry}
        material={nodes.janela010_Plane002.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela011_Plane003.geometry}
        material={nodes.janela011_Plane003.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela012_Plane006.geometry}
        material={nodes.janela012_Plane006.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela013_Plane009.geometry}
        material={nodes.janela013_Plane009.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela014_Plane018.geometry}
        material={nodes.janela014_Plane018.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1007_Roundcube013.geometry}
        material={nodes.carruagem1007_Roundcube013.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1008_Roundcube014.geometry}
        material={nodes.carruagem1008_Roundcube014.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1009_Roundcube015.geometry}
        material={nodes.carruagem1009_Roundcube015.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1010_Roundcube016.geometry}
        material={nodes.carruagem1010_Roundcube016.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1011_Roundcube017.geometry}
        material={nodes.carruagem1011_Roundcube017.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1_Roundcube018.geometry}
        material={nodes.carruagem1_Roundcube018.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.parte_debaixo_Roundcube019.geometry}
        material={nodes.parte_debaixo_Roundcube019.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1013_Roundcube020.geometry}
        material={nodes.carruagem1013_Roundcube020.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.motor_e_rodas_5.geometry}
        material={nodes.motor_e_rodas_5.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.motor_e_rodas_4.geometry}
        material={nodes.motor_e_rodas_4.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1014_Roundcube021.geometry}
        material={nodes.carruagem1014_Roundcube021.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.Roundcube045.geometry}
        material={nodes.Roundcube045.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela015_Plane019.geometry}
        material={nodes.janela015_Plane019.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela016_Plane020.geometry}
        material={nodes.janela016_Plane020.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela017_Plane021.geometry}
        material={nodes.janela017_Plane021.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela018_Plane022.geometry}
        material={nodes.janela018_Plane022.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1012_Roundcube024.geometry}
        material={nodes.carruagem1012_Roundcube024.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1015_Roundcube025.geometry}
        material={nodes.carruagem1015_Roundcube025.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1016_Roundcube026.geometry}
        material={nodes.carruagem1016_Roundcube026.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1017_Roundcube027.geometry}
        material={nodes.carruagem1017_Roundcube027.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1018_Roundcube028.geometry}
        material={nodes.carruagem1018_Roundcube028.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1019_Roundcube029.geometry}
        material={nodes.carruagem1019_Roundcube029.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1020_Roundcube030.geometry}
        material={nodes.carruagem1020_Roundcube030.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1021_Roundcube031.geometry}
        material={nodes.carruagem1021_Roundcube031.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1022_Roundcube032.geometry}
        material={nodes.carruagem1022_Roundcube032.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela004_Plane004.geometry}
        material={nodes.janela004_Plane004.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1023_Roundcube034.geometry}
        material={nodes.carruagem1023_Roundcube034.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela005_Plane005.geometry}
        material={nodes.janela005_Plane005.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela019_Plane023.geometry}
        material={nodes.janela019_Plane023.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela020_Plane024.geometry}
        material={nodes.janela020_Plane024.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela021_Plane025.geometry}
        material={nodes.janela021_Plane025.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1024_Roundcube035.geometry}
        material={nodes.carruagem1024_Roundcube035.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1025_Roundcube036.geometry}
        material={nodes.carruagem1025_Roundcube036.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela022_Plane026.geometry}
        material={nodes.janela022_Plane026.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela023_Plane027.geometry}
        material={nodes.janela023_Plane027.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela024_Plane028.geometry}
        material={nodes.janela024_Plane028.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela025_Plane029.geometry}
        material={nodes.janela025_Plane029.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela026_Plane030.geometry}
        material={nodes.janela026_Plane030.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela027_Plane031.geometry}
        material={nodes.janela027_Plane031.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela028_Plane032.geometry}
        material={nodes.janela028_Plane032.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela029_Plane033.geometry}
        material={nodes.janela029_Plane033.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela030_Plane034.geometry}
        material={nodes.janela030_Plane034.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela031_Plane035.geometry}
        material={nodes.janela031_Plane035.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.janela032_Plane036.geometry}
        material={nodes.janela032_Plane036.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.Roundcube046.geometry}
        material={nodes.Roundcube046.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.Plane004_Plane037.geometry}
        material={materials["Material.021"]}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.parte_debaixo001.geometry}
        material={materials["Material.023"]}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, -0.58]}
      />
      <group position={[11.4, 0.71, 0]} scale={[0.9, 0.58, -0.58]}>
        <mesh
          castShadow
          geometry={nodes.Roundcube050.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          castShadow
          geometry={nodes.Roundcube050_1.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          castShadow
          geometry={nodes.Roundcube050_2.geometry}
          material={materials["Material.026"]}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.carruagem1030.geometry}
        material={materials["Material.027"]}
        position={[12.55, 0.8, 0]}
        scale={[1.33, 0.58, -0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1031.geometry}
        material={materials["Material.028"]}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, -0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1032.geometry}
        material={materials["Material.029"]}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, -0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1028.geometry}
        material={materials["Material.034"]}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, -0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.Plane.geometry}
        material={materials["Vidro.001"]}
        position={[4.89, 0.66, 0]}
        rotation={[0, 0, -0.05]}
        scale={[1.16, 1.39, 1.16]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1004.geometry}
        material={materials["Material.002"]}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.porta001.geometry}
        material={materials["Material.005"]}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.porta2.geometry}
        material={materials["Material.011"]}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1026.geometry}
        material={materials["Material.008"]}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <group position={[18.09, 0.71, 0]} scale={[0.78, 0.58, -0.58]}>
        <mesh
          castShadow
          geometry={nodes.Roundcube069.geometry}
          material={materials["Material.033"]}
        />
        <mesh
          castShadow
          geometry={nodes.Roundcube069_1.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          castShadow
          geometry={nodes.Roundcube069_2.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          castShadow
          geometry={nodes.Roundcube069_3.geometry}
          material={materials["Material.032"]}
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.porta002.geometry}
        material={materials["Material.006"]}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.porta002_Roundcube040.geometry}
        material={materials["Material.020"]}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.porta2001.geometry}
        material={materials["Material.007"]}
        position={[11.4, 0.71, 0]}
        scale={[0.9, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1027.geometry}
        material={nodes.carruagem1027.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1029.geometry}
        material={nodes.carruagem1029.material}
        position={[18.09, 0.71, 0]}
        scale={[0.78, 0.58, 0.58]}
      />
      <mesh
        castShadow
        geometry={nodes.Plane_Plane007.geometry}
        material={materials["Vidro.003"]}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.porta001_Roundcube004.geometry}
        material={materials["Material.016"]}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1004_Roundcube010.geometry}
        material={materials["Material.014"]}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.porta2_Roundcube023.geometry}
        material={materials["Material.017"]}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1026_Roundcube038.geometry}
        material={nodes.carruagem1026_Roundcube038.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1028_Roundcube042.geometry}
        material={nodes.carruagem1028_Roundcube042.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1027_Roundcube039.geometry}
        material={nodes.carruagem1027_Roundcube039.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.carruagem1029_Roundcube043.geometry}
        material={nodes.carruagem1029_Roundcube043.material}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        castShadow
        geometry={nodes.porta2001_Roundcube041.geometry}
        material={materials["Material.022"]}
        position={[37.85, 0, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      />
    </group>
  );
}

useGLTF.preload("/models/train_1/train.glb");
